 
name: Spellcheck

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@0.33.1
        with:
          config_path: .github/spellcheck.yml

